#!/bin/bash

PACKAGE_PATH=/usr/pkg

# Helper functions for creating and editing the package config

# Create the package - a package is just a directory containing a ini file with
# information about the package
create_pkg() {
    [ $# -eq 0 ] \
        && echo "No package name provided" \
        && exit 1

    [ ! -d $PACKAGE_PATH ] \
        && echo "Please create $PACKAGE_PATH to proceed" \
        && exit 1

    echo "Creating package $1 in $PACKAGE_PATH/$1"

    [ ! -d $PACKAGE_PATH/$1 ] \
        && mkdir $PACKAGE_PATH/$1

    [ -e $PACKAGE_PATH/$1/PKGBUILD ] \
        && echo "Package already exists!" \
        && exit 1

    touch $PACKAGE_PATH/$1/PKGBUILD
    cat << EOF > $PACKAGE_PATH/$1/PKGBUILD
#!/bin/bash
#
# [General]
#
# [Version]
# stable_version=
# version_listing=
# version_scheme=
# latest_version=
#
# [Build]
# distfiles=
#
# [Dependencies]
# depends_on=
# depended_on_by=
# lock=
EOF
    echo "Created package $1 successfully"
    exit 0
}

# Retrieve a key from a package
get_pkg_data() {
    [ $# -eq 0 ] \
        && echo "No package name provided" \
        && exit 1

    [ $# -eq 1 ] \
        && echo "No configuration option selected" \
        && exit 1

    [ ! -e $PACKAGE_PATH/$1/PKGBUILD ] \
        && echo "Could not find configuration for package $2" \
        && exit 1

    sed -n "s@#\s*$2=\s*\(.*\)\($\)@\1@" $1
}

# Change a key in a package
change_pkg_data() {
    [ $# -eq 0 ] \
        && echo "No package name provided" \
        && exit 1

    [ $# -eq 1 ] \
        && echo "No configuration option selected" \
        && exit 1

    [ ! -e $PACKAGE_PATH/$1/PKGBUILD ] \
        && echo "Could not find package configuration" \
        && exit 1

    sed -i "s@#\s*$2=\(.*\)\($\)@\0$3@" $1
}

# Add a key to a package
add_pkg_data() {
    [ $# -eq 0 ] \
        && echo "No package name provided" \
        && exit 1

    [ $# -eq 1 ] \
        && echo "No configuration option selected" \
        && exit 1

    [ ! -e $PACKAGE_PATH/$1/PKGBUILD ] \
        && echo "Could not find package configuration" \
        && exit 1

    sed -i "s@#\[General\]@\0\n#\ $2=$3@" $1
}

# Set a key in a package
set_pkg_data() {
    [ $# -eq 0 ] \
        && echo "No package name provided" \
        && exit 1

    [ $# -eq 1 ] \
        && echo "No configuration option selected" \
        && exit 1

    [ -z $(get_pkg_data $1 $2) ] \
        && add_pkg_data $1 $2 $3 \
        && exit 1

    change_pkg_data $1 $2 $3
}
